### ISSUE TITLE
AjaxCallback - handle own responses

### ISSUE THREAD

**Issue by gpoitch** [tinyeeliu/androidquery#8]
A service I am calling returns status code 422 for invalid login (wrong password, etc)
However, it still returns a valid JSON response along with it, which includes error messages.

AjaxCallback does'nt seem to return the JSON in that case

I see this in the source:
        if(code < 200 || code >= 300)

**Comment by tinyeeliu** [comment]
Try AjaxStatus.getError() should return the result as a string in case of error. You can then create a JSONObject from it.

The reason that the object is null is because there's no guarantee what the error return type is. It could be html, text from the web server and rarely a JSON. In this case AQuery just return the result as a generic string.

**Comment by gpoitch** [comment]
Thanks, that solution will work
